### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by m0sth8** [bearded-web/bearded#38]
https://github.com/bearded-web/frontend/issues/46

 - [x] add reset-password endpoint
 - [x] add tokens for password reset
 - [x] send token to email ( #59 )
 - [x] add check-token endpoint
 - [x] invalidate token (remove invalid token with cronjob)
 - [x] add beautiful templates for email

**Comment by slonoed** [comment]
@m0sth8 я тут подумал, что пользователя из мейла надо не в интерфейс возвращать на хешурл с токеном. А сначала на сервер, где ты будешь смотреть, валидный ли токен еще. Если валидный, то редиректишь на хешурл, если нет, то на логин.
Или если невалидный, то добавляешь в хешурл еще параметр. Тогда я смогу пользователю показывать либо форму либо инфу, что токен устарел.
А то сейчас получится, что пользователь с тухлым токеном получит форму нормальную, введет в нее чтото и получит ошибку.

**Comment by slonoed** [comment]
Workflow
- Client send to `POST /api/v1/auth/reset-password` with `email` field. Swagger `resetPassword`.
- If no email, server respond error (Email not found). Stop.
- If email email find, server respond OK
- Server generate new token for this user, with expire time equal 1 day
- Server send email to user with link `GET http://{domain}/api/v1/auth/reset-password?token={token}&email={email}`
- User click link
- Server check token for user
- If token not good. Server redirect to `http://{domain}/#/reset-end?error={errorMessage}`. Stop.
- If token ok, server redirect to `http://{domain}/#/reset-end?token={token}`.
- Client send `PUT http://{domain}/api/v1/me/password` with body `{ new: "{new password}", token: "{token}"`. Swagger `changePassword`
- If token or password invalid, server send error. Stop.
- If token and password ok, server send OK.
- Server delete token.

Notice:
- Email provider should be plugable. Settings store in backend config. Better if it support sendgird and similar.
- If each token unique for all users collection (token hash source contain email), email param in link can be omitted.
- Endpoint can be changed before coding
- Expire date for tokens must be configurable.
- User can create many tokens. And each must be valid (until used, or expired)

**Comment by m0sth8** [comment]
Change urls from -> to:
/api/v1/me/reset-password -> /api/v1/auth/reset-password
http://{domain}/api/v1/reset-password?token={token}&email=email -> http://{domain}/reset-password?token={token}&email=email

**Comment by m0sth8** [comment]
Email template https://github.com/leemunroe/responsive-html-email-template
